# Generated by Django 5.1.15 on 2026-08-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_group_url', models.URLField(blank=True)),
                ('telegram_group_url', models.URLField(blank=True)),
                ('payee_name', models.CharField(blank=True, max_length=120)),
                ('payment_code', models.CharField(blank=True, max_length=60)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fallback_referrer', models.ForeignKey(blank=True, help_text='Users who sign up without a referral code are attributed to this admin.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
