# Generated by Django 5.1.15 on 2026-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="International format without '+', e.g. 250783108892 (used for the WhatsApp chat link).", max_length=20),
        ),
    ]
