# Generated by Django 5.1.15 on 2026-08-20 14:39

from django.db import migrations, models


def turn_notice_on(apps, schema_editor):
    """Show the notice as soon as this deploys; staff untick it in admin when the system is back."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(maintenance_notice=True)


def turn_notice_off(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(maintenance_notice=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesettings_whatsapp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_message",
            field=models.CharField(
                blank=True,
                default="The display system has a technical problem. Our team is fixing it - please wait.",
                help_text="Text shown in the site-wide notice.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_notice",
            field=models.BooleanField(
                default=False,
                help_text="Show a site-wide notice on every page. Untick it as soon as the system is back.",
            ),
        ),
        migrations.RunPython(turn_notice_on, turn_notice_off),
    ]
