# Generated by Django 5.1.15 on 2026-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_maintenance_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_whatsapp",
            field=models.CharField(
                blank=True,
                default="250795927291",
                help_text="WhatsApp number for help during the outage. International format without '+' or the leading 0, e.g. 250795927291 for 0795 927 291 - wa.me links do not work with the local format.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="maintenance_message",
            field=models.CharField(
                blank=True,
                default="The display system has a technical problem. Our team is fixing it - please wait.",
                help_text="Text shown on the maintenance page.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="maintenance_notice",
            field=models.BooleanField(
                default=False,
                help_text="Replace the whole site with the maintenance page. Visitors see nothing else until this is unticked - staff and the admin are never blocked.",
            ),
        ),
    ]
