# Generated by Django 5.1.15 on 2026-08-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_maintenance_whatsapp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="maintenance_message",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="maintenance_notice",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="maintenance_whatsapp",
        ),
    ]
